import Head from "next/head";
import Auth from "../components/AuthPage";
import BooksList from "../components/booksLists";


export default function Index() {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
          <Auth />
      </main>
        <BooksList />
    </div>
  );
}
