# Generated by Django 3.2.6 on 2021-12-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20211227_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
