# Generated by Django 3.2.6 on 2021-12-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_delete_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'verbose_name': 'Tweet', 'verbose_name_plural': 'Tweets'},
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='date',
            new_name='created_at',
        ),
    ]
